version: '3.9'

services:
  keycloak:
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USER: keycloak
      KC_DB_PASSWORD: TopSecretDBPassword4Keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    image: quay.io/keycloak/keycloak:23.0
    command: start-dev 
    restart: unless-stopped
    ports:
      - 8080:8080

  postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: TopSecretDBPassword4Keycloak
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

